# Generated by Django 5.2 on 2025-04-20 20:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningfile',
            name='file',
            field=models.FileField(upload_to=core.models.get_hashed_filename),
        ),
    ]
