# Generated by Django 5.2 on 2025-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_learningfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload_file', 'Upload File'), ('create_topic', 'Create Topic'), ('edit_topic', 'Edit Topic'), ('delete_topic', 'Delete Topic'), ('delete_file', 'Delete File'), ('create_course', 'Create Course'), ('edit_course', 'Edit Course'), ('delete_course', 'Delete Course'), ('add_member', 'Add Member'), ('approve_group', 'Approve Group'), ('reject_group', 'Reject Group'), ('update_profile', 'Update Profile')], max_length=20),
        ),
        migrations.AlterField(
            model_name='learningfile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('code', 'Code'), ('document', 'Document'), ('video', 'Video'), ('audio', 'Audio'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
