# Generated by Django 5.2 on 2025-04-24 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_profile_photo_alter_activitylog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningfile',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learningfile',
            name='share_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='learningfile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('upload_file', 'Upload File'), ('create_topic', 'Create Topic'), ('edit_topic', 'Edit Topic'), ('delete_topic', 'Delete Topic'), ('delete_file', 'Delete File'), ('create_course', 'Create Course'), ('edit_course', 'Edit Course'), ('delete_course', 'Delete Course'), ('add_member', 'Add Member'), ('approve_group', 'Approve Group'), ('reject_group', 'Reject Group'), ('update_profile', 'Update Profile'), ('view_file', 'View File'), ('download_file', 'Download File'), ('comment_file', 'Comment on File'), ('like_file', 'Like File'), ('share_file', 'Share File'), ('report_file', 'Report File')], max_length=20),
        ),
        migrations.CreateModel(
            name='FileInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('comment', 'Comment'), ('like', 'Like')], max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.learningfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('inappropriate_content', 'Inappropriate Content'), ('copyright_violation', 'Copyright Violation'), ('spam', 'Spam'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.learningfile')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_files', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('file_interaction', 'File Interaction'), ('new_file', 'New File'), ('report_update', 'Report Update'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.learningfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.report')),
            ],
        ),
    ]
