# Generated by Django 5.2 on 2025-04-27 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commentreport_groupinvitation_groupleaderboard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitation',
            name='accepted_by',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='email',
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='is_multiple_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='usage_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fileinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('view', 'View'), ('download', 'Download'), ('comment', 'Comment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='InvitationUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uses', to='core.groupinvitation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accepted_at'],
                'unique_together': {('invitation', 'user')},
            },
        ),
    ]
