# Generated by Django 5.2 on 2025-04-27 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_groupinvitation_accepted_by_and_more'),
    ]

    operations = [
        # Remove the old role field from User
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),

        # Add new is_super_admin field
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),

        # Create the GroupMembership model
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('user', 'User')], default='user', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),

        # Use SeparateDatabaseAndState to update the model state without changing the database
        # This avoids the error when trying to change a ManyToManyField to use a through model
        migrations.SeparateDatabaseAndState(
            # Don't make any database changes
            database_operations=[],
            # But update the Django model state to use the through model
            state_operations=[
                migrations.AlterField(
                    model_name='studygroup',
                    name='members',
                    field=models.ManyToManyField(related_name='study_groups', through='core.GroupMembership', to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
