# Generated by Django 5.2 on 2025-04-27 21:14

from django.db import migrations


def create_group_memberships(apps, schema_editor):
    """
    Convert existing group memberships to use the new GroupMembership model
    and assign roles based on previous relationships.
    """
    User = apps.get_model('core', 'User')
    StudyGroup = apps.get_model('core', 'StudyGroup')
    GroupMembership = apps.get_model('core', 'GroupMembership')

    # Set super_admin status for users who were previously super_admin
    for user in User.objects.all():
        # Since role field is already removed, we'll set super admins based on the group creator status
        if user.created_groups.filter(status='approved').exists():
            user.is_super_admin = True
            user.save()

    # For each group, create group memberships for all members
    for group in StudyGroup.objects.all():
        # Group creator is always an admin
        if group.created_by:
            GroupMembership.objects.get_or_create(
                user=group.created_by,
                group=group,
                defaults={'role': 'admin'}
            )

        # Other members get 'user' role by default
        for user in group.members.all().exclude(pk=group.created_by.pk):
            GroupMembership.objects.get_or_create(
                user=user,
                group=group,
                defaults={'role': 'user'}
            )


def reverse_group_memberships(apps, schema_editor):
    """
    No actual reverse operation needed as we're not removing data
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_role_add_super_admin'),
    ]

    operations = [
        # Run the data migration to create the group memberships
        migrations.RunPython(create_group_memberships, reverse_group_memberships),
    ]
